In [14]:
import pandas as pd

In [16]:
pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset4/main/sales_data.csv')

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001"
...,...,...,...,...,...,...
796,237436,USB-C Charging Cable,1,11.95,08/18/19 19:41,"83 2nd St, Dallas, TX 75001"
797,237437,AAA Batteries (4-pack),2,2.99,08/23/19 19:14,"496 Main St, Seattle, WA 98101"
798,237438,27in 4K Gaming Monitor,1,389.99,08/08/19 15:09,"496 South St, Dallas, TX 75001"
799,237439,Bose SoundSport Headphones,1,99.99,08/07/19 14:26,"675 Lake St, Los Angeles, CA 90001"
800,237440,AAA Batteries (4-pack),1,2.99,08/11/19 19:50,"775 8th St, Portland, OR 97035"